#!/bin/bash

# change to ';' for Cygwin
SEP=':'

# collect all the jar names
for jar in ../lib/**/*.jar
  do
  # Check for no expansion
  [ -e "$jar" ] || break
  #echo "Path: $jar"
  [ "$CP" != "" ] && CP="${CP}${SEP}"
  CP="${CP}$jar"
done

CP=$CP:../classes

# echo java -cp $CP org.hyperdata.scute.rdf.ModelToJSON $1

java -cp $CP org.hyperdata.scute.rdf.ModelToJSON $1